# 应用服务 WEB 访问端口
server:
  port: 8080

## spring security配置
#spring:
# security:
#    user:
#      name: root
#      password: 123

# Spring配置
#spring:
#  # 模板引擎
#  thymeleaf:
#    mode: HTML
#    encoding: utf-8
#    # 禁用缓存
#    cache: false